name: CI

on:
  push:

  workflow_dispatch:


permissions:
  id-token: write
  contents: read
jobs:

  terraform-deploy:

    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS Credentials for China region audience
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::308082261316:role/infra-practice-github-role

      - name: Deploy Terraform Infra
        directory: root-module
        run: |
          terraform init
          terraform plan -var-file=dev.tfvars


